language: go

go:
  - 1.5.3

sudo: false

before_install:
  - go get github.com/golang/lint/golint

install: true

script:
  - sed -i "s/zenlinTechnofreak/containerops/g" `go list ./... |grep zenlinTechnofreak -rl`
  - go test -v $(go list ./... | grep -v /vendor/)
  - go vet -x ./...
  - $HOME/gopath/bin/golint $(go list ./... | grep -v /vendor/)
  - go build
